stages:
  data_ingestion:
    cmd: python src\components\data\ingestion.py
    deps:
      - src\components\data\ingestion.py
      - config/config.yaml
    outs:
      - artifacts\data\ingestion\raw\Chicken-fecal-images


  data_preprocessing:
    cmd: python src\components\data\preprocessing.py
    deps:
      - src\components\data\preprocessing.py
      - config/config.yaml
    outs:
      - artifacts\data\preprocessing

  

  evaluation:
    cmd: python src\components\model\evaluation.py
    deps:
      - src\components\model\evaluation.py
      - config/config.yaml
      - artifacts\data\preprocessing
    outs:
      - artifacts\model\callbacks\tensorboard_dir
    
